### ISSUE TITLE
nbextensions.py incorrectly terminates jQuery string

### ISSUE THREAD

**Issue by brunobeltran** [ipython-contrib/IPython-notebook-extensions#236]
The symptom is a *completely* blank /nbextensions/ page. 

The reason appears to be that in config/main.js, the line `$('body').data('extension-list')` incorrectly returns a string instead of a list of JSON objects. (Leading to an error on line 35ish when the variable `extensions` is a character from a string instead of a JSON object with member 'Name').

The cause of this appears to be that the data-extension-list attribute of $('body') is incorrectly terminated. In my case it ends up being of the form (note the missing terminating `}]`):
```
[{"Link": "https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Codefolding", "Name": "Codefolding", "url": "nbextensions/usability/codefolding", "Icon": "icon.png", "Main": "main.js", "Type": "IPython Notebook Extension", "Compatibility": "3.x", "Description": "This extension enables the CodeMirror feature to llow codefolding in code cells"}, ... , {"Link": "https://github.com/jfbercher/IPython-notebook-extensions/tree/master/testing/latex_envs/", "Name": "(some) LaTeX environments for Jupyter", "url": "nbextensions/testing/latex_envs", "Icon": "icon.png", "Main": "latex_envs.js", "Type": "IPython Notebook Extension", "Compatibility": "3.x", "Description": "Enable to use laTeX environments in Jupyter"
```

Adding the terminating `}]` manually and rerunning main.js fixes the problem (as long as I flush jQuery's .data() cache). 

I understand that this data field is populated from inside of config/nbextension.py, but running said file by hand in an iPython shell line by line leaves `json_list` populated correctly (i.e. with the terminal `}]` included). This seems to suggest that the problem is in the function self.render_template or self.write

Unfortunately, I can't get these guys to print to any files by adding debug statements for some reason...

So I'm stuck with a very hack-y workaround of manually modifying the data string from inside main.js on page load. 

In a ?potentially related bug? all div's appear to have `display: none` set on page load. So without my workaround, not even the header with the Jupyter logo is visible. For some reason, I can fix the `display: none` problem by deleting everything in my nbextensions directory except for the files needed for the `/nbextensions/` page to load. I assume that this is because in this case the `extensions_list` is empty, so that main.js gets to the point where it loads the page's CSS or something like that.

**Comment by juhasch** [comment]
Fixed by #237

**Comment by brunobeltran** [comment]
Not actually fixed. I still need to include the following for the page to show correctly on my computer. I didn't include this in my pull request since it's clearly a temporary hack that doesn't get at the underlying problem:
```
diff --git a/config/main.js b/config/main.js
index ec6d932..d770120 100644
--- a/config/main.js
+++ b/config/main.js
@@ -25,6 +25,8 @@ require([

     var base_url = utils.get_body_data('baseUrl');
     var extension_list = $('body').data('extension-list');
+    extension_list = extension_list.concat('"}]');
+    extension_list = jQuery.parseJSON(extension_list);

     var html = "";
```

**Comment by juhasch** [comment]
If you have single quotes in the YAML file description line, this will make JSON parsing fail in Javascript. This is fixed by #240. You can take a look at the JSON string transferred from Python to Javascript by looking at the page source code and look for `data-extension-list=...`

**Comment by brunobeltran** [comment]
Oh I see. Thanks so much for the pointer!

**Comment by brunobeltran** [comment]
Alright, I'm sure I'm starting to sound like a broken record, but this issue is not fixed, and concerns the 3.x branch, which was not addressed in #240 . As I stated before, in nbextensions.py, line 50 or so, json_list is correctly populated. It is only in the actual writing of the variable that for some reason the last three characters get cut off.

Is the bug itself clear?

**Comment by juhasch** [comment]
OK, yes.
Is the json list already truncated when you look at the pages source code in the `data-extension-list`, or does it happen later in Javascript ?

**Comment by jcb91** [comment]
#284 shows the same behaviour, even with the #240, I'm not entirely sure how it's managing not to be escaped. In addition, with the new nestable yaml format from #274 (which could allow the Parameters yaml value to contain, for example, a list of strings as a default for one of the parameters), escaping each yaml value is no longer sufficient.

I've cooked up a solution by using the jinja template escape filter to escape the json string, which I can submit a PR for, but it brings into play a few other potential issues, which I think might be worth considering before adopting it:

The [html 4 spec](http://www.w3.org/TR/REC-html40/sgml/sgmldecl.html) seems to limit the length of data attributes to 65536 bytes (see the tag `ATTSPLEN`). While this may or may not actually be true in a given user agent, it seems like it'd be better not to have it break things inexplicably. Also, although 64KiB seems like a lot, since each `'` becomes `&39;` when escaped, and the escaping is also applied to every `"` in the json, it gets longer quite quickly. Mine is already 16KiB. Since support arbitrary strings in parameter values (which could end up quite long), it would make sense to think about circumventing this limitation.

I propose the following solution:
* have the html template add the urls of the extension specification (yaml) files, rather than their contents, and then load them using javascript
* ditch YAML in favour of JSON for the specification files, to not rely on javascript yaml-parsing
* require the extension specification files to have a specific name (e.g. `nbextension-spec.json`), since JSON files may be in use in extensions for a variety of purposes.

Any thoughts?

**Comment by juhasch** [comment]
I think you are right, it it not desirable to manually escape all of information we want to send to the Javascript part of the extension. On the other hand I greatly prefer the yaml format over json for humans, and it looks like dealing with yaml in Python is the better approach.

Your idea of using the Jinja template system looks good. I tried this `data-extension-list='{{extension_list|e}}` in the `nbextensions.html` template and does what we need.

Regarding the 64k limit, I think the right thing to do would be to either warn or raise an exception when the list is too large.

**Comment by jcb91** [comment]
Right, YAML certainly reads nicer, and works fine for the python side. I think it's certainly possible to work around YAML ok, even if it's as simple as splitting into multiple data attributes if one ends up >64k

Ok, having given it a little more inspection, all the Jinja escaping (which is provided by [markupsafe](https://github.com/mitsuhiko/markupsafe)) actually does is replace `'`, `"`, `<`, `>`, `&`. In an attribute string, therefore, the only character which should actually need escaping is the single quote - as you correctly deduced previously. So, a fix which might be better could be to just escape the single quotes in the json-ified data string, rather than in the source YAML keys/values. That way, we avoid escaping all the rather numerous double-quotes in the json (which the jinja solution does), while being more robust than trying to escape individual key/value elements.

I think raising an exception (or at least logging a warning) on failure to write/read the data attribute is also a good idea. I'll get onto it.

**Comment by juhasch** [comment]
I guess what you propose is the best approach for now. The Jinja approaches escapes a lot more than necessary, it seems.

**Comment by jcb91** [comment]
I've submitted a PR for this on #292
